version: 0.2

phases:
  build:
    commands:
    - echo "This is build phase......LL Zipping my lambda function"
    - zip -r deployment_package.zip *
  post_build:
    commands:
    - echo "Deploying to the Lambda..!!"
   
    - aws lambda update-function-code --function-name  demotemp --zip-file fileb://deployment_package.zip
